
export const products = [
    {
      id: 1,
      name: 'Garlic Bread',
      href: '#',
      price: 35 ,
      imageSrc: 'https://thebusybaker.ca/wp-content/uploads/2018/08/easy-homemade-garlic-bread-fbig3.jpg',
      imageAlt: 'Garlic Bread',
    },
    {
      id: 2,
      name: 'Chocolate Chip Cookies',
      href: '#',
      price: 25 ,
      imageSrc: 'https://assets.bonappetit.com/photos/5ca534485e96521ff23b382b/1:1/w_2700,h_2700,c_limit/chocolate-chip-cookie.jpg',
      imageAlt: 'Chocolate Chip Cookies',
    },
    {
      id: 3,
      name: 'Macaron',
      href: '#',
      price: 40,
      imageSrc: 'https://sugargeekshow.com/wp-content/uploads/2022/12/italian_macaron_Featured.jpg',
      imageAlt: 'Macaron',
    },
    {
      id: 4,
      name: 'Vanilla Cupcakes',
      href: '#',
      price: 40 ,
      imageSrc: 'https://www.recipetineats.com/tachyon/2020/09/Vanilla-Cupcakes-with-Vanilla-Swiss-Meringue-SQ.jpg',
      imageAlt: 'Vanilla Cupcakes',
    },
    {
      id: 5,
      name: 'Panna Cotta',
      href: '#',
      price: 45 ,
      imageSrc: 'https://assets.epicurious.com/photos/62d6c513077a952f4a8c338c/1:1/w_2848,h_2848,c_limit/PannaCotta_RECIPE_04142022_9822_final.jpg',
      imageAlt: 'Panna Cotta',
    },
    {
      id: 6,
      name: 'Chocolate Cake',
      href: '#',
      price: 45,
      imageSrc: 'https://sugargeekshow.com/wp-content/uploads/2023/10/easy_chocolate_cake_slice.jpg',
      imageAlt: 'Chocolate Cake',
    },
    {
      id: 7,
      name: 'Banana Cake',
      href: '#',
      price: 50 ,
      imageSrc: 'https://d34zicoa2zcr2f.cloudfront.net/sites/files/bakersbrewstudio2/productimg/202204/800xAUTO/1x1_bakersbrew_thebetterbananaloaf_3.png',
      imageAlt: 'Banana Cake',
    },
    {
      id: 8,
      name: 'Pretzels',
      href: '#',
      price: 35 ,
      imageSrc: 'https://handletheheat.com/wp-content/uploads/2021/09/soft-pretzel-recipe-SQUARE.jpg',
      imageAlt: 'Pretzels',
    },
    {
      id: 9,
      name: 'Egg Tart',
      href: '#',
      price: 25 ,
      imageSrc: 'https://bakes-saigon.com/cdn/shop/products/EGG_TART_3.jpg?v=1702475752',
      imageAlt: 'Egg Tart',
    },
    {
      id: 10,
      name: 'Croissant',
      href: '#',
      price: 55 ,
      imageSrc: 'https://static01.nyt.com/images/2021/04/07/dining/06croissantsrex1/06croissantsrex1-square640.jpg',
      imageAlt: 'Croissant',
    },
    {
      id: 11,
      name: 'Toast',
      href: '#',
      price: 100,
      imageSrc: 'https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2024-04-french-toast%2Ffrench-toast-COMP',
      imageAlt: 'Toast',
    },
    {
      id: 12,
      name: 'Apple Pie',
      href: '#',
      price: 250 ,
      imageSrc: 'https://static01.nyt.com/images/2023/11/09/multimedia/09piesrex3-apple/09piesrex4-lemon-cqtk-square640.jpg',
      imageAlt: 'Apple Pie',
    }
  ]
